### PR TITLE
Add TokenValidationParametersCreated notification

### PR DESCRIPTION
**Pull request by explunit**
This allows customization of audience, issuer, etc. beyond what the core library would support.

### CODE REVIEW

**Comment by AndersAbel** [comment]
Yes, the `TokenValidationParameters` need to be exposed for the end user to alter. The way the other protocol handlers this is however done in another way: They have a `TokenValidationParameters` instance as part of the options. For each validation operation that instance is then cloned to a new instance. The per-request parameters are then set on that cloned instance. E.g. the `RequireSignedTokens` parameter (if we use the built in signature validation) would be set to false for a token received through a signed message.

That doesn't exclude the possibility to have a notification like this though - a notification would give the user a last chance to alter the settings before they are used. I'm not sure that is a good idea though. Because this would open for the kind of "bug fixes" where someone would fix a signature problem by setting `RequiredSignedTokens` to false.

What do you think? Would a "template" `TokenValidationParameters` in the options solve most use cases?

**Comment by explunit** [comment]
It would solve most, but I think there are some cases that it would not. For example, the current code directly sets a single expected audience but if someone wanted to allow multiple audience values they would have no ability to do that.

The above might be a contrived example (and contrary to the SAML spec), but looking at the current code that's the sequence of calls that I would worry about.

**Comment by AndersAbel** [comment]
I think we should keep the idea of implementing a "template" `TokenValidationParameters` in the future, keeping in line with the other protocol handlers.

But I still think this PR has value. However I'm considering if it should somehow be named in a way to indicate that using it makes it possible to do unsafe things.

One idea would be to put it under a a separate sub-property in the `Saml2Notifications` class: `Saml2Notifications.Unsafe.TokenValidationParametersCreated`. We could also do a similar thing in the compatibility section.

Further I think that we should consider including some kind of state in the param list. I've found out that it's a general flaw with the notifications. In many cases there's no way to get any additional state or info about the current request/SAML message/Active Idp which makes it hard to implement conditional checks/modifications.

**Comment by explunit** [comment]
I've made more state available to the notification (IDP, XmlElement). I was undecided about `XmlElement` but I see that it's already exposed as a public property. Let me know if you disagree about sending this to the notification.

Regarding naming: I'm not opposed to moving it, but I'm not sure about "unsafe". I don't see how modifying the `TokenValidationParameters` at this stage is less safe than providing a template that sets `ValidateAudience` to false (for example).

**Comment by AndersAbel** [comment]
Even with the template, I think that the most important validation params will be validated/set. E.g. the signature validation params will be set for each request (I do plan to move to use the built in signature validator instead of `SignedXml`). So even with a template, I would try to add some kind of safety net against the most stupid configurations. The notification would then provide a "do whatever you want at your own risk" possibility. That's why I'm considering a name indicating that it is dangerous.

And once more this is a discussion about a potential future that might or might not become reality. The problem is that once we release this as a public API we're stuck with the naming.

**Comment by explunit** [comment]
OK, makes sense. I've moved it to a new `Notifications.Unsafe` section.

**Pull request merged**
