### PR TITLE
Break out Metadata to separate library

### PR DESCRIPTION
**Pull request by rpmansion**
Move metadata codes from Sustainsys.Saml2 to Sustainsys.Saml2.Metadata project except for codes related to loader and scheduler.

### CODE REVIEW

**Comment by rpmansion** [comment]
@AndersAbel should we use the `EntityId` from `IdentityModel`? If yes, will remove the one in the code base.

**Comment by AndersAbel** [comment]
> @AndersAbel should we use the `EntityId` from `IdentityModel`? If yes, will remove the one in the code base.

What assembly is it in?

**Comment by rpmansion** [comment]
> What assembly is it in?

System.IdentityModel

**Comment by AndersAbel** [comment]
> > What assembly is it in?
> 
> There is one in `System.IdentityModel` and one in `Sustainsys.Saml2.Metadata`

As far as I know the one in `System.IdentityModel` is not available in .NET Core. That's the reason we created an own one.

**Comment by rpmansion** [comment]
> As far as I know the one in System.IdentityModel is not available in .NET Core. That's the reason we created an own one.

I see. Upon checking again, still not available in .NET Core

**Comment by rpmansion** [comment]
@AndersAbel need to rerun the action, I'm getting all of the test as passed on my local

**Comment by AndersAbel** [comment]
Ignore it, the report says "internal error". I hope the next commit will work.

**Comment by rpmansion** [comment]
@AndersAbel I've moved codes of the metadata except the loader and scheduler

**Comment by AndersAbel** [comment]
@rpmansion Sounds great. I'll have a look and get it merged.

**Comment by rpmansion** [comment]
@AndersAbel reviewing the code base, what is the reason why we do not maximize the use of `System.Security.Cryptography.Xml` instead of creating our own classes that are already exist in such library?

**Comment by AndersAbel** [comment]
> @AndersAbel reviewing the code base, what is the reason why we do not maximize the use of `System.Security.Cryptography.Xml` instead of creating our own classes that are already exist in such library?

Do you have an example? I can think of two reasons: 1. It was not available on .NET Core when the port was done. 2. It doesn't contain all the properties to properly represent the metadata.

**Comment by AndersAbel** [comment]
Good first step to breaking metadata out to a separate library. Thanks!

**Comment by rpmansion** [comment]
@AndersAbel can we link this to the issue? Thank you for merging, will further add new changes. :)

**Pull request merged**
