### PR TITLE
Added XmlCreated event to allow for change of raw XML data

### PR DESCRIPTION
**Pull request by nojan1**
Add XmlCreated event to Saml2RequestBase that fires during the execution of ToXml. This allows the user to manipulate the raw XML before it is send to the IDP.

### CODE REVIEW

**Comment by therrealdude** [comment]
Is there a way to do this in the current state of the package? I need the exact same thing.

**Comment by AndersAbel** [comment]
@therrealdude This is a good idea, but the PR was made before the switch to the libraries for .NET Core. As the conflicts indicates, it requires some work before merge is possible.

I'd suggest that you pull this down, rebase it and create a new PR against the current master.

**Comment by therrealdude** [comment]
@AndersAbel , I created the change. I'm a little new to github. I created a branch, but it won't let me push it to your repo. Do I need your permissions or is the norm to fork it, then open a pull request to your branch?

**Comment by AndersAbel** [comment]
@therrealdude You have to fork it, push the updated version to a branch in your fork and then create a PR.

**Pull request closed without merging**
