### PR TITLE
Add new identity provider configuration to allow unsigned log out request/response

### PR DESCRIPTION
**Pull request by cederlof**
Code from @MinhNguyenDev PR: https://github.com/Sustainsys/Saml2/pull/590 which is based on an old version of Saml2 (and had conflicts with master).

This is the solution for issue #446, adding two new parameters to the IdentityProvider-element in config:
allowUnsignedLogOutRequest and allowUnsignedLogOutResponse. For use when the IDP does not support signing of log out request/response.

```

<identityProviders>
  <add entityId="https://app.onelogin.com/saml/metadata"
       signOnUrl="one login sso log in url"
       logoutUrl="one login sso log out url"
       allowUnsignedLogOutRequest="true" 
       allowUnsignedLogOutResponse="true" 
       binding="HttpRedirect">
        ....
  </add>
</identityProviders>
```

### CODE REVIEW

**Comment by ricardosaracino** [comment]
Question, is this going to be rolled in ever?

**Comment by cederlof** [comment]
Hi! The fix resolves the feature for unsigned logout responses, however not allowing unsigned logout requests.

**Comment by AndersAbel** [comment]
@cederlof Yes, that's true. And per the discussion in the other PR we limited it to responses for security reasons. Allowing unsigned logout requests open up for some kinds of attacks and I am very reluctant to add compatibility flags that allows unsecure usage of the library.
What is the background for the requirement of unsigned logout requests?

**Comment by cederlof** [comment]
@AndersAbel I agree with your reasoning! We do not have a requirement for unsigned logout requests, but I thought it would be good to mention as this PR was labeled `duplicate`.

**Pull request closed without merging**
