### PR TITLE
Added new compatibility option IgnoreMissingInResponseTo. 

### PR DESCRIPTION
**Pull request by TalalTayyab**
Added new compatibility option IgnoreMissingInResponseTo. so it will not throw an exception in the Saml response if the InResponseTo attribute is missing.
a
Based on the discussion in #482 , it was suggested to add this option in ```Compatibility``` class.

### CODE REVIEW

**Comment by TalalTayyab** [comment]
@AndersAbel just wondering if this PR can be merged in :) - trying to avoid creating a fork. I think it adds value as its been requested multiple times. Thanks.

**Comment by alohaninja** [comment]
any progress with this - this error **Received message contains unexpected InResponseTo "idbxxxxxxxxxxxxx". No RelayState was detected so message was not expected to have an InResponseTo attribute.** is occurring regularly with many of our SAML integrations, would love to see this compatibility option get merged in - regardless of what the spec says, we have little control over how the vendor follows the specifications.

**Comment by TalalTayyab** [comment]
@explunit  - I have just done a merge with master and there are no conflicts.

**Comment by arneeiri** [comment]
So you guys with write access. Any chance this will make it in?

**Comment by AndersAbel** [comment]
@arneeiri Yes, it's on my review queue so eventually it will be handled. But for the work I do for free I cannot guarantee any timeframe. If you need this, please consider my commercial services to get priority to this.

**Pull request closed without merging**
